[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.devnet]
maxi_farm = "maxi7YSyG2Fpuh9hNzjojuV7woB9PTV4fRwZZ523ayu"

[programs.localnet]
maxi_farm = "maxi7YSyG2Fpuh9hNzjojuV7woB9PTV4fRwZZ523ayu"

[programs.mainnet]
maxi_farm = "maxi7YSyG2Fpuh9hNzjojuV7woB9PTV4fRwZZ523ayu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://indulgent-polished-knowledge.solana-mainnet.quiknode.pro/614b45582ce4805ce1eda829737192cf0a90bf93/"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/maxi_farm.ts"
